default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: notifications_service_development

test:
  <<: *default
  database: notifications_service_test

production:
  <<: *default
  database: notifications_service_production
  username: notifications_service_user
  password: <%= ENV['NOTIFICATIONS_SERVICE_DATABASE_PASSWORD'] %>
